# Generated by Django 5.2.5 on 2025-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=100, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price in USD', max_digits=8)),
                ('category', models.CharField(choices=[('ELEC', 'Electronics'), ('CLOT', 'Clothes'), ('BOOK', 'Books')], default='ELEC', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
